lesson6_homework
phenomiks/design_patterns pull request #4
Opened 2021-07-12 18:29 UTC by phenomiks

[Урок 6. Архитектурные системные паттерны. Часть 1] Домашняя работа

2021-07-14 16:59 UTC, dikkini requested changes

2021-07-14 16:59 UTC, dikkini commented on less6_data_mapper/src/main/java/ru/geekbrains/patterns/identitymap/ProductIdentityMap.java
> +        productMap.put(product.getId(), product);
вызова БД не хватает

2021-07-14 16:59 UTC, dikkini commented on less6_data_mapper/src/main/java/ru/geekbrains/patterns/identitymap/ProductIdentityMap.java
> +        return productMap.get(id);
вызова БД не хватает если нет в кеше

2021-07-16 19:01 UTC, phenomiks commented on less6_data_mapper/src/main/java/ru/geekbrains/patterns/identitymap/ProductIdentityMap.java
> +        return productMap.get(id);
Исправлено

2021-07-16 19:01 UTC, phenomiks commented on less6_data_mapper/src/main/java/ru/geekbrains/patterns/identitymap/ProductIdentityMap.java
> +        productMap.put(product.getId(), product);
Исправлено

2021-09-22 14:06 UTC, merged